version: 2.1
jobs:
  build:
    executor: python/default
    steps:
      - checkout
      - python/load-cache
      - python/install-deps
      - python/install-deps:
          dependency-file: "requirements-dev.txt"
      - python/save-cache
      - run:
          command: |
            pip install .
          name: pip install .
      - run:
          command: |
            # pytest would be a dep in requirements.txt
            pytest
          name: Test
orbs:
  python: circleci/python@0.3.2

workflows:
  main:
    jobs:
      - build