version: 2.1

jobs:
  build:
    docker:
      - image: cimg/python:3.8
      - image: influxdb:latest
    steps:
      - checkout
      - run:
          command: |
            pip install .
          name: pip install .
      - run:
          command: |
            # InfluxDB onboarding
            wget -S --spider --tries=20 --retry-connrefused --waitretry=5 http://localhost:8086/metrics
            curl -i -X POST http://localhost:8086/api/v2/setup -H 'accept: application/json' -d '{"username": "my-user","password": "my-password","org": "my-org","bucket": "my-bucket","token": "my-token"}'
      - run:
          command: |
            # pytest would be a dep in requirements.txt
            pytest
          name: Test

workflows:
  main:
    jobs:
      - build