version: 2.1
jobs:
  build:
    executor: python/default
    docker:
      - image: quay.io/influxdb/influxdb:2.0.0-beta
    steps:
      - checkout
      - python/load-cache
      - python/install-deps
      - python/install-deps:
          dependency-file: "requirements-dev.txt"
      - python/save-cache
      - run:
          command: |
            pip install .
          name: pip install .
      - run:
          command: |
            # InfluxDB onboarding
            wget -S --spider --tries=20 --retry-connrefused --waitretry=5 http://localhost:9999/metrics
            curl -i -X POST http://localhost:9999/api/v2/setup -H 'accept: application/json' -d '{"username": "my-user","password": "my-password","org": "my-org","bucket": "my-bucket","token": "my-token"}'
      - run:
          command: |
            # pytest would be a dep in requirements.txt
            pytest
          name: Test
orbs:
  python: circleci/python@0.3.2

workflows:
  main:
    jobs:
      - build